name: CrinkleCruftPlugin
main: com.crinklecruft.crinkleplugin.App
version: 0.1
authors: [MrBean1512, Nathaniel Graham]
api-version: 1.13
commands:
   comTest:
      description: This command does nothing.
      usage: /<command> [player]
      permission: CrinkleCruftPlugin.comTest
      permission-message: You don't have <permission> to execute this command
   testAction:
      description: Test actions through this class.
      usage: /<command> [player]
      permission: CrinkleCruftPlugin.testAction
      permission-message: You don't have <permission> to execute this command